-- ===================================================================
-- PostGIS-equivalent schema for the facility access database
-- Generated by 03_spatial_database_pipeline.py
--
-- The delivered database is DuckDB + spatial (PostGIS is not installable in
-- the assessment environment). This file is the same schema expressed for a
-- ministry PostGIS server: identical primary keys, identical foreign keys,
-- identical CHECK constraints, typed and SRID-constrained geometry columns,
-- and GiST indexes in place of DuckDB's R-tree indexes.
--
-- Storage CRS  : EPSG:4326  (WGS 84 geographic)
-- Analysis CRS : 102022  ESRI:102022 (Africa Albers Equal Area Conic)
-- ===================================================================

CREATE EXTENSION IF NOT EXISTS postgis;
CREATE SCHEMA IF NOT EXISTS facility_access;
SET search_path TO facility_access, public;

-- Africa Albers Equal Area Conic is not in the stock spatial_ref_sys table.
INSERT INTO public.spatial_ref_sys (srid, auth_name, auth_srid, proj4text, srtext)
VALUES (102022, 'ESRI', 102022,
        '+proj=aea +lat_0=0 +lon_0=25 +lat_1=20 +lat_2=-23 +x_0=0 +y_0=0 +datum=WGS84 +units=m +no_defs',
        'PROJCS["Africa_Albers_Equal_Area_Conic",GEOGCS["GCS_WGS_1984",'
        'DATUM["D_WGS_1984",SPHEROID["WGS_1984",6378137.0,298.257223563]],'
        'PRIMEM["Greenwich",0.0],UNIT["Degree",0.0174532925199433]],'
        'PROJECTION["Albers"],PARAMETER["False_Easting",0.0],'
        'PARAMETER["False_Northing",0.0],PARAMETER["Central_Meridian",25.0],'
        'PARAMETER["Standard_Parallel_1",20.0],PARAMETER["Standard_Parallel_2",-23.0],'
        'PARAMETER["Latitude_Of_Origin",0.0],UNIT["Meter",1.0]]')
ON CONFLICT (srid) DO NOTHING;

CREATE TABLE states (
    state_code  text            NOT NULL PRIMARY KEY,
    state_name  text            NOT NULL UNIQUE,
    geom        geometry(Polygon, 4326) NOT NULL
);

CREATE TABLE senatorial_districts (
    sen_code      text NOT NULL PRIMARY KEY,
    sen_district  text NOT NULL UNIQUE,
    state_code    text NOT NULL REFERENCES states(state_code) ON UPDATE CASCADE,
    geom          geometry(Polygon, 4326) NOT NULL
);

CREATE TABLE lgas (
    lga_code    text NOT NULL PRIMARY KEY,
    lga_name    text NOT NULL,
    sen_code    text NOT NULL REFERENCES senatorial_districts(sen_code) ON UPDATE CASCADE,
    state_code  text NOT NULL REFERENCES states(state_code) ON UPDATE CASCADE,
    geom        geometry(MultiPolygon, 4326) NOT NULL
);

CREATE TABLE wards (
    ward_code          text   NOT NULL PRIMARY KEY,
    ward_name          text   NOT NULL,
    lga_code           text   NOT NULL REFERENCES lgas(lga_code) ON UPDATE CASCADE,
    sen_code           text   NOT NULL REFERENCES senatorial_districts(sen_code) ON UPDATE CASCADE,
    state_code         text   NOT NULL REFERENCES states(state_code) ON UPDATE CASCADE,
    total_population   bigint NOT NULL CHECK (total_population >= 0),
    population_under5  bigint NOT NULL CHECK (population_under5 >= 0),
    population_source  text   NOT NULL,
    geom               geometry(Polygon, 4326) NOT NULL,
    CONSTRAINT ck_wards_under5_le_total CHECK (population_under5 <= total_population)
);

CREATE TABLE staffing_norms (
    facility_type            text    NOT NULL PRIMARY KEY,
    min_medical_officers     integer NOT NULL CHECK (min_medical_officers     >= 0),
    min_nurses_midwives      integer NOT NULL CHECK (min_nurses_midwives      >= 0),
    min_chews                integer NOT NULL CHECK (min_chews                >= 0),
    min_lab_scientists       integer NOT NULL CHECK (min_lab_scientists       >= 0),
    min_pharmacy_technicians integer NOT NULL CHECK (min_pharmacy_technicians >= 0),
    adequacy_rule            text    NOT NULL
);

CREATE TABLE lga_senatorial_crosswalk (
    lga_code            text NOT NULL PRIMARY KEY REFERENCES lgas(lga_code) ON UPDATE CASCADE,
    lga_name            text NOT NULL,
    lga_name_source     text,
    sen_code            text NOT NULL REFERENCES senatorial_districts(sen_code) ON UPDATE CASCADE,
    sen_district        text NOT NULL,
    state_code          text NOT NULL REFERENCES states(state_code) ON UPDATE CASCADE,
    state_name          text NOT NULL,
    ward_count_declared integer,
    ward_count_observed integer,
    remarks             text,
    match_method        text   NOT NULL,
    match_confidence    double precision NOT NULL CHECK (match_confidence BETWEEN 0 AND 1),
    match_outcome       text   NOT NULL
        CHECK (match_outcome IN ('resolved','resolved_review','unresolved','conflict')),
    source_sheet_row    integer
);

CREATE TABLE facilities (
    facility_id        text   NOT NULL PRIMARY KEY,
    facility_name      text   NOT NULL,
    facility_type      text   NOT NULL REFERENCES staffing_norms(facility_type) ON UPDATE CASCADE,
    ownership          text   NOT NULL CHECK (ownership IN ('Public','Private','Faith-based')),
    ward_code          text   NOT NULL REFERENCES wards(ward_code) ON UPDATE CASCADE,
    lga_code           text   NOT NULL REFERENCES lgas(lga_code) ON UPDATE CASCADE,
    sen_code           text   NOT NULL REFERENCES senatorial_districts(sen_code) ON UPDATE CASCADE,
    state_code         text   NOT NULL REFERENCES states(state_code) ON UPDATE CASCADE,
    declared_ward_name text,
    declared_lga_name  text,
    ward_assignment    text   NOT NULL
        CHECK (ward_assignment IN ('within_polygon','snapped_to_nearest')),
    longitude          double precision NOT NULL CHECK (longitude BETWEEN -180 AND 180),
    latitude           double precision NOT NULL CHECK (latitude  BETWEEN  -90 AND  90),
    coord_status       text   NOT NULL,
    coord_parse_method text   NOT NULL,
    geom               geometry(Point, 4326) NOT NULL
);

-- A separate 1:1-optional table, so that "never assessed" is representable as
-- the absence of a row rather than as a row of zeros.
CREATE TABLE facility_staffing (
    facility_id        text NOT NULL PRIMARY KEY
                       REFERENCES facilities(facility_id) ON DELETE CASCADE ON UPDATE CASCADE,
    med_officers       integer NOT NULL CHECK (med_officers    >= 0),
    nurses_midwives    integer NOT NULL CHECK (nurses_midwives >= 0),
    chews              integer NOT NULL CHECK (chews           >= 0),
    lab_scientists     integer NOT NULL CHECK (lab_scientists  >= 0),
    pharm_techs        integer NOT NULL CHECK (pharm_techs     >= 0),
    personnel_score    double precision NOT NULL,
    sen_rank           integer,
    staffing_status    text NOT NULL CHECK (staffing_status IN ('adequate','inadequate')),
    staffing_shortfall text,
    binding_cadres     integer NOT NULL,
    binding_cadres_met integer NOT NULL,
    CONSTRAINT ck_staffing_met_le_binding CHECK (binding_cadres_met <= binding_cadres)
);

CREATE TABLE roads (
    road_id      text NOT NULL PRIMARY KEY,
    road_class   text NOT NULL,
    surface      text NOT NULL,
    speed_kmh    double precision NOT NULL CHECK (speed_kmh > 0),
    length_m     double precision NOT NULL CHECK (length_m  > 0),
    traverse_min double precision NOT NULL,
    geom         geometry(LineString, 4326) NOT NULL
);

CREATE TABLE ward_access (
    ward_code                    text NOT NULL PRIMARY KEY
                                 REFERENCES wards(ward_code) ON UPDATE CASCADE,
    facilities_total             integer NOT NULL,
    facilities_adequate          integer NOT NULL,
    facilities_inadequate        integer NOT NULL,
    facilities_unknown           integer NOT NULL,
    travel_min_to_adequate       double precision,
    travel_min_to_any            double precision,
    covered_60min                boolean NOT NULL,
    population_covered           double precision NOT NULL,
    population_uncovered         double precision NOT NULL,
    access_deficit               double precision NOT NULL,
    gap_type                     text NOT NULL,
    priority_rank                integer
);

CREATE TABLE qa_facilities_unlocated (
    facility_id      text NOT NULL PRIMARY KEY,
    facility_name    text NOT NULL,
    facility_type    text NOT NULL,
    ownership        text,
    declared_ward_name text,
    declared_lga_name  text,
    raw_longitude    text,
    raw_latitude     text,
    coord_status     text NOT NULL,
    exclusion_reason text NOT NULL
);

CREATE TABLE qa_scores_unregistered (
    facility_id      text NOT NULL PRIMARY KEY,
    facility_name    text,
    personnel_score  double precision,
    longitude        double precision,
    latitude         double precision,
    exclusion_reason text NOT NULL
);

CREATE TABLE reconciliation_ledger (
    ledger_id      bigserial PRIMARY KEY,
    stage          text NOT NULL,
    source         text NOT NULL,
    entity_id      text,
    field          text NOT NULL,
    raw_value      text,
    resolved_value text,
    method         text NOT NULL,
    confidence     double precision NOT NULL CHECK (confidence BETWEEN 0 AND 1),
    outcome        text NOT NULL
        CHECK (outcome IN ('resolved','resolved_review','unresolved','conflict')),
    note           text
);

-- ------------------------------------------------------------------
-- Spatial indexes (GiST) and attribute indexes
-- ------------------------------------------------------------------
CREATE INDEX idx_states_geom     ON states     USING GIST (geom);
CREATE INDEX idx_sen_geom        ON senatorial_districts USING GIST (geom);
CREATE INDEX idx_lgas_geom       ON lgas       USING GIST (geom);
CREATE INDEX idx_wards_geom      ON wards      USING GIST (geom);
CREATE INDEX idx_facilities_geom ON facilities USING GIST (geom);
CREATE INDEX idx_roads_geom      ON roads      USING GIST (geom);

CREATE INDEX idx_facilities_ward ON facilities (ward_code);
CREATE INDEX idx_facilities_lga  ON facilities (lga_code);
CREATE INDEX idx_facilities_type ON facilities (facility_type);
CREATE INDEX idx_wards_lga       ON wards      (lga_code);
CREATE INDEX idx_lgas_sen        ON lgas       (sen_code);
CREATE INDEX idx_staffing_status ON facility_staffing (staffing_status);
CREATE INDEX idx_ledger_outcome  ON reconciliation_ledger (outcome);

-- ------------------------------------------------------------------
-- Governance views
-- ------------------------------------------------------------------

-- Where the Surveyor General's crosswalk and the boundary layer disagree.
CREATE OR REPLACE VIEW v_crosswalk_divergence AS
SELECT x.lga_code, x.lga_name,
       x.sen_district  AS crosswalk_assignment,
       s.sen_district  AS boundary_layer_assignment,
       x.remarks
FROM   lga_senatorial_crosswalk x
JOIN   lgas l                 ON l.lga_code = x.lga_code
JOIN   senatorial_districts s ON s.sen_code = l.sen_code
WHERE  x.sen_code <> l.sen_code;

-- Ward-level supply, keeping "not assessed" distinct from "inadequate".
CREATE OR REPLACE VIEW v_ward_supply AS
SELECT w.ward_code, w.ward_name, w.lga_code, w.sen_code, w.total_population,
       count(f.facility_id)                                       AS facilities_total,
       count(*) FILTER (WHERE s.staffing_status = 'adequate')     AS facilities_adequate,
       count(*) FILTER (WHERE s.staffing_status = 'inadequate')   AS facilities_inadequate,
       count(*) FILTER (WHERE f.facility_id IS NOT NULL
                          AND s.facility_id IS NULL)              AS facilities_unassessed
FROM   wards w
LEFT   JOIN facilities f        ON f.ward_code   = w.ward_code
LEFT   JOIN facility_staffing s ON s.facility_id = f.facility_id
GROUP  BY w.ward_code, w.ward_name, w.lga_code, w.sen_code, w.total_population;
